### PR TITLE
Base contribution

### PR DESCRIPTION
**Pull request by blackwine93v**

### CODE REVIEW

**Comment by osarrouy** [comment]
Hey !

Thanks for the update. This seems to fix the build issue though there is still a unmeet peer dependency:

```
ttypescript@1.5.10" has unmet peer dependency "ts-node@^8.0.2".
```

`tsnode` should be added in the `devDependencies`.

Also copying `privacy.wasm` into the root folder of the project won't fix the loading issue cause its path is computed relatively to where the program is executed.

I think the relative path [here](https://github.com/incognitochain/sdk-v2/blob/bc806bc21a2b52b520af90ccc1325f69b4f39ff0/src/go/wasm/index.ts#L12) should simply be harcoded.

**Comment by blackwine93v** [comment]
Put the wasm binary file at the root folder is good enough. Maybe the sdk will have an option to config the wasm path, I guess 😆

Btw, dont worry about the unmet warning.

**Comment by osarrouy** [comment]
Hey,

Sorry to be a pain in the ass but I don't understand why you say that putting the wasm binary file at the root folder is 'good enough' when it's obviously not. It basically makes using the SDK to built something on node impossible ...

**Comment by blackwine93v** [comment]
Sorry, maybe I misunderstood your issue, but after coping wasm binary file to my root project folder, it works (new wallet was created successfully)

Please see my project screen shoot
Screen Shot 2020-04-06 at 20 44 37

Let me know if the problem still happens.

**Comment by osarrouy** [comment]
No worries :)

It works in your case cause you're running `index.js` in the very same folder your `privacy.wasm` binary lies. Now if you turn this script into a cli tool hosted for instance in `/usr/share/bin` with the wasm binary and call it from somewhere else - for instance you home directory - it won't work.

**Comment by blackwine93v** [comment]
I added a wasmPath config to the SDK, it will help you config your own wasm path, please check this commit 224e504

Thanks

**Comment by osarrouy** [comment]
This looks good to me!

**Comment by osarrouy** [comment]
Any idea when this will be merged ?

**Pull request merged**
